languageCode = "en-us"
title = "WAF Assesment"

uglyURLs = true
contentDir = "templates"
layoutDir = "templates"
publishDir = "output"
disableKinds = ["RSS", "sitemap"]

[mediaTypes]
   [mediaTypes."text/html"]
     suffixes = ["md"]
     
[outputFormats]
   [outputFormats.HTML]
     mediaType = "text/html"
     