# This is a basic workflow to help you get started with Actions

name: HugoDocs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ nielshugopoc ]

jobs:
  HugoGenerate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: srt32/hugo-action@master
        name: Create a new Hugo Environment
        with: 
          args: new site waf --force

      #- name: Setup the files in the Hugo structure
        #run: |
          #sudo mkdir waf/layouts/waf
          #sudo mkdir waf/content/waf
          #sudo touch waf/content/waf/waf.md

          #sudo cp data/*.json waf/data
          #sudo cp template/reliabilityassessment.md waf/layouts/waf/waf.html

      - name: Move files into the Hugo directories
        shell: pwsh
        run: |
          # Make a nice sudo function in powershell :)
          function Invoke-MySudo { & /usr/bin/env sudo pwsh -command "& $args" }
          set-alias sudo invoke-mysudo 

          # Give Hugo some data files:
          Get-ChildItem -R data | where { $_.Name -match ".json$" } | % { sudo Copy-Item -Path $_.FullName -Destination "waf/data/$($_.Name)"  }
          
          # Each directory in the template directory must be copied to Hugo.
          Get-ChildItem -Directory template | % {
            # Create project directories under content and layouts:
            sudo New-Item -ItemType Directory -Path "waf/content/$($_.Name)"
            sudo New-Item -ItemType Directory -Path "waf/layouts/$($_.Name)"

            # The content directories each need an empty .md file in them
            sudo New-Item -ItemType File -Path "waf/content/$($_.Name)/$($_.Name).md"

            # The template files have to be in the project directories under layouts, with html extensions:
            Get-ChildItem -Path template/$($_.Name) | % {
              $filename = $_.Name -replace "\.md$",""
              sudo Copy-Item -Path $_.FullName -Destination "waf/layouts/$filename.html"
            }            
          }

      - uses: srt32/hugo-action@master
        name: Build Hugo content
        with: 
          args: -s waf

      - name: Show all files
        shell: pwsh
        run: |
          gci -Recurse

      - name: Copy files out of Hugo
        shell: pwsh
        run: |
          # Process the output for each of the 'projects' that went in
            Get-ChildItem -Directory template | % {
              New-Item -ItemType Directory -Path "output/$($_.Name)" -Force
              Copy-Item -Path "waf/public/$($_.Name)/index.html" -Destination "output/$($_.Name)/$($_.Name).md"
            }

      - name: Show all files
        shell: pwsh
        run: |
          gci -Recurse

      - name: Push files to repo
        shell: pwsh
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'nielsactiontest@users.noreply.github.com'
     
          git add 'output/'
          git status --short

          $message = git log -1 --pretty=format:"%s"

          if(git status -uno --short) {
            git commit -am "Auto update: $message"
            git push origin
          } 
          else {
            Write-Output "No changes to commit. Bye."
          }