on:
  pull_request:
    branches: [main]

jobs:
  build:
    # Name the Job
    name: Lint Content
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      # Checkout the content
      - name: Checkout Content
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
  
      # Run Linter against content
      - name: Lint Content
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}